name: smads_example
description: Demonstrates how to use the smads plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  smads:
    path: ../

flutter:
  uses-material-design: true
