name: smads
description: A new flutter plugin project.
version: 1.1.0+1
homepage: https://github.com/suamusica

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.suamusica.smads
    pluginClass: SmadsPlugin
