name: smads
description: A new flutter plugin project.
version: 1.0.4
homepage: https://github.com/suamusica

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.suamusica.smads
    pluginClass: SmadsPlugin