name: snowplow
description: A new flutter plugin project.
version: 1.0.0
homepage: https://github.com/suamusica

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.suamusica.snowplow
    pluginClass: SnowplowPlugin