name: equalizer
description: SMEqualizer
version: 0.0.4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.suamusica.equalizer
        pluginClass: EqualizerPlugin
      ios:
        pluginClass: EqualizerPlugin
