name: smplayer
description: A new flutter plugin project.
version: 1.0.5
homepage: https://github.com/suamusica
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

isar_version: &isar_version 3.1.0

dependencies:
  flutter:
    sdk: flutter
  mutex: ^3.0.1
  isar: *isar_version
  isar_flutter_libs: *isar_version
  path_provider: ^2.0.11
  file_picker:
    git:
      url: https://github.com/SuaMusica/flutter_file_picker.git
      ref: 528cd01a317b45305d293c03e855ec7255c3ab59
  smaws:
    git:
      url: https://github.com/SuaMusica/flutter_plugins.git
      path: packages/aws/

dev_dependencies:
  build_runner: ^2.2.1
  isar_generator: *isar_version
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: br.com.suamusica.player
    pluginClass: PlayerPlugin
