name: smplayer
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  uuid: ^2.0.2
  flutter:
    sdk: flutter
  smaws:
    git: 
      url: https://github.com/SuaMusica/flutter_plugins.git 
      path: packages/aws/

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: br.com.suamusica.player
    pluginClass: Plugin
