name: suamusica_player
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  uuid: ^2.0.2
  equatable: ^0.3.0
  flutter:
    sdk: flutter
  aws:
    path: ../aws

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: br.com.suamusica.player
    pluginClass: Plugin