name: smplayer
description: A new flutter plugin project.
version: 1.0.5
homepage: https://github.com/suamusica
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

isar_version: &isar_version ^3.2.0 # define the version to be used

dependencies:
  flutter:
    sdk: flutter
  mutex: ^3.1.0
  isar_community: *isar_version
  isar_community_flutter_libs: *isar_version
  path_provider: ^2.1.5
  smaws:
    git:
      url: https://github.com/SuaMusica/flutter_plugins.git
      path: packages/aws/
      ref: feature/16kb

dev_dependencies:
  build_runner: ^2.2.1
  isar_community_generator: *isar_version
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: br.com.suamusica.player
    pluginClass: PlayerPlugin
