name: smplayer
description: A new flutter plugin project.
version: 1.0.0
author:  Sua Música
homepage: https://github.com/suamusica
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mutex: ^2.0.0
  smaws:
    git: 
      url: https://github.com/SuaMusica/flutter_plugins.git 
      path: packages/aws/
      ref: feature/nullSafetyUpgrade
  uuid: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: br.com.suamusica.player
    pluginClass: PlayerPlugin
