enum EventType {
  PLAY_REQUESTED,
  BEFORE_PLAY,
  BUFFERING,
  PLAYING,
  PAUSE_REQUEST,
  PAUSED,
  RESUME_REQUESTED,
  RESUMED,
  STOP_REQUESTED,
  STOPPED,
  RELEASE_REQUESTED,
  RELEASED,
  DURATION_CHANGE,
  POSITION_CHANGE,
  REWIND,
  PREVIOUS,
  FORWARD,
  NEXT,
  FINISHED_PLAYING,
  ERROR_OCCURED,
  NETWORK_CHANGE,
  SEEK_START,
  SEEK_END,
  BUFFER_EMPTY,
  EXTERNAL_RESUME_REQUESTED,
  EXTERNAL_PAUSE_REQUESTED,
}

enum PlayerErrorType {
  FAILED,
  UNKNOWN,
  UNDEFINED,
  FAILED_TO_PLAY,
  FAILED_TO_PLAY_ERROR,
  NETWORK_ERROR,
  INFORMATION,
}

extension FeedTypeString on PlayerErrorType {
  String get toShortString =>
      this.toString().replaceAll("PlayerErrorType.", "");
}
