name: smaws
description: AWS SDK related functionality.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  convert: ^2.1.1
  rsa_pkcs: ^1.1.4  
  pointycastle: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.2

flutter:
  assets:
    - assets/