name: suamusica_player_example
description: Demonstrates how to use the suamusica_player plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  aws:
    path: ../../aws

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  suamusica_player:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - assets/