name: smplayer_example
description: Demonstrates how to use the suamusica_player plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  smaws:
    git:
      url: https://github.com/SuaMusica/flutter_plugins.git 
      path: packages/aws/

  flutter_svg: ^0.21.0-nullsafety.0
  cupertino_icons: ^1.0.2
  smplayer:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
