name: smplayer_example
description: Demonstrates how to use the suamusica_player plugin.
publish_to: 'none'

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  smaws:
    path: ../../aws

  flutter_svg: ^0.14.1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  smplayer:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - assets/